# Generated by Django 3.2.9 on 2021-12-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_name'),
        ('posts', '0004_alter_post_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='categories.Category'),
        ),
    ]
