# Generated by Django 3.2.9 on 2021-12-09 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211207_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_users',
            field=models.ManyToManyField(default='self', related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
