# Generated by Django 3.2.9 on 2021-12-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_file',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
