export { Biology } from './Biology'
export { Chemistry } from './Chemistry'
export { Computing } from './Computing'
export { English } from './English'
export { Maths } from './Maths'
export { Physics } from './Physics'