# Generated by Django 3.2.9 on 2021-12-07 14:26

from django.conf import settings
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_remove_post_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=models.SET(posts.models.get_deleted_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
