# Generated by Django 3.2.9 on 2021-12-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_categories',
            field=models.ManyToManyField(to='categories.Category'),
        ),
    ]
