# Generated by Django 3.2.9 on 2021-12-07 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_name'),
        ('users', '0005_auto_20211207_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_categories',
            field=models.ManyToManyField(blank=True, to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followed_users',
            field=models.ManyToManyField(blank=True, related_name='_users_user_followed_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
